    
    
# Bot prefix
    prefix: "!!"

# Server ID
    serverID: "269812518002753537"
    
# ID of the owner of the server 
    ownerID: "238825468864888833"
    
# Log Channel - Channel Mimsy will log server inputs to.
    logChannelID: "415987090480955392"

# Mimsy-Talk Channel - Channel where mimsy will respond to messages
    mimsyChannelID: "498905030875807776"
    
# Soundboard Channel
    soundboardChannelID: "414497480928133120"

# Test Channel
    testChannelID: "378315211607769089"

# Suggestions channel (only Mimsy should post here)
    suggestionsChannelID: "418370942356684800"

# Streaming channel where new subscribers and stream information is announced
    YouTubeChannelID: "416757328528932875"

# Moderation Log channel (only Mimsy should post here)
    moderationChannelID: "421701938195857438"

# ROLES
    flowerRoleID: "404647452201844736"

    bananaRoleID: "325737032972238850"

    followerRoleID: "418524770448048129"

    noTagRoleID: "410461710332329985"

    VIPRoleID: "309191262274191362"

# APIS
    youtubeAPIKEY: "AIzaSyDdqQwb7UMmJ5edznE3OPwX4-F7_CxS0OM"

# Youtube Integration
    songSelectionSize: 5

# Daily Greeting
    dailyGreeting: true
    
#List channels where YT videos are allowed to be posted:
    allowedYTChannelIDs: [546653815701766164,532946538884759624, 532637708271616000, 378315211607769089, 317066233230917632, 343748288702578689, 311545553198645248, 441680626869993472]

#Milliseconds between Youtube API requests.
    updateInterval: 10000

#Emojis
    mockbob: <:mockbob:378998241787641866>

#- Specify number of top players you want to display for medals
    TopPlayers: 3

#- Specify the name of the currency you want to give (Medals by default) This changes the !getpoints / !addpoints command to !addmedals/!getmedals
    points: "medals"

#- Specify main command to add rewards to users (prefix + addPoints + user + amount)
    addPoints: "medal"

#- Console welcome message
    welcome: "Discord Bot: Mimsy has launched!"

#- Hangman Difficulty: 1:"easy" 2:"medium" 3:"hard" 4:"insane"
    hangmanDifficulty: 2